Initial fox to switch order of preference for using docstring annotat…
mkdocstrings/pytkdocs pull request #110
Opened 2021-09-08 01:21 UTC by ghandic

Initial fox to switch order of preference for using docstring annotations over signature annotations in the 'docstring_sections' value of the output

2021-09-10 10:37 UTC, pawamoy requested changes

2021-09-10 10:37 UTC, pawamoy commented on src/pytkdocs/parsers/docstrings/google.py
> +            self.error("No return type annotation")
We shouldn't log an error if there is a return annotation.

2021-09-10 10:37 UTC, pawamoy commented on src/pytkdocs/parsers/docstrings/google.py
> +                #     annotation = signature_param.annotation
Shouldn't this condition be moved in the `else` clause line 249 instead? We *do* want to use annotations if there's no type in the docstring.

2021-09-10 10:38 UTC, pawamoy commented
Thanks! I just added two comments.

2021-09-10 23:11 UTC, ghandic commented
Thanks for the review, I think I have fixed the issues you've pointed out. If not then I think it might be worth adding some extra test cases of examples where it could break

2021-09-14 16:42 UTC, pawamoy commented
Great, thanks! The comments are especially appreciated! I'll run this locally to see how it behaves, and we should be good to go.

2021-09-17 04:40 UTC, ghandic commented
Are there any fixes needed here? Or gtg?

2021-09-21 17:06 UTC, pawamoy commented
Hey @ghandic, thank you again, I'll merge this and release it in version 0.12.0 :slightly_smiling_face:

2021-09-21 17:12 UTC, pawamoy approved these changes

2021-09-21 17:14 UTC, merged